### ISSUE TITLE
Can't get sysinfo.3s.sh to run

### ISSUE THREAD

**Issue by afettouhi** [roachsinai/k-argos-plugins#1]
As you suggested I am creating issue as we discussed in the plasma-applet-thermal-monitor
 thread. I am running Arch Linux on a i7-6700K with a GTX 1080 Nvidia card using KDE Plasma 5. I have installed the kargos widget and downloaded the sysinfo.3s.sh into my home folder (also chmodded the file) plus the font used has been installed from AUR. Running the script with kargos just shows me a starting... in the widget. Running it directly in a konsole gives this output

```
[af@andre Hentninger]$ ./sysinfo.3s.sh
<u>34</u>°<u></u>&nbsp;<u>29</u>°|font=iosevka size=14 color=white
---
CPU: .1% |font=iosevka size=14 color=white
MEM: 12.7% |font=iosevka size=14 color=white
```

**Comment by roachsinai** [comment]
Yeah, I have three questions, look forward to your answer.

![image](https://user-images.githubusercontent.com/9500049/64909473-3befe600-d73f-11e9-98d3-b69b0a87608c.png)

1. Have you modified the script path to your home folder at kargos setting as above?
2. How you installed kargos? Did you follow https://github.com/lipido/kargos#installation 
 or downloaded from ked store?
3. Have you tried the examples at kargos repo,  if not please have a try.

**Comment by afettouhi** [comment]
Just close this. I failed at the first question. I was pointing to the script in my home folder but I had the script actually placed in the Downloads folder DOH!!! BTW is there a way to modify the script to show the temperature of the HDD's and the individual cores?

**Comment by roachsinai** [comment]
Sure.

```
(nn) hmank ~ » qdbus --system org.freedesktop.UDisks2 /org/freedesktop/UDisks2/drives/Samsung_SSD_750_EVO_250GB_S3J2NB0HB04700N org.freedesktop.UDisks2.Drive.Ata.SmartTemperature
305.15000000000003
(nn) hmank ~ » qdbus --system org.freedesktop.UDisks2 | grep SSD                             
/org/freedesktop/UDisks2/drives/Samsung_SSD_750_EVO_250GB_S3J2NB0HB04700N
```

based on https://github.com/kotelnik/plasma-applet-thermal-monitor/blob/783536952c38bf26aefadb36d2dadd50c8ddc2c0/package/contents/code/model-utils.js#L144

Maybe you could find all thing at plasma-applet-thermal-monitor excpet Cpu and memory usage.

So you can `grep HDD` get the detail of your hard disk and modify it.

**Comment by afettouhi** [comment]
Not quite sure I understand what you mean.

**Comment by roachsinai** [comment]
First you should use `qdbus --system org.freedesktop.UDisks2 | grep HDD` to get specific name of your `HDD` here we use hdd1, then use

`qdbus --system org.freedesktop.UDisks2 /org/freedesktop/UDisks2/drives/hdd1 org.freedesktop.UDisks2.Drive.Ata.SmartTemperature` to get what you need, if this command do make it, just add it to your script.

**Comment by afettouhi** [comment]
Hmm... for some reason
`qdbus --system org.freedesktop.UDisks2 | grep HDD`

doesn't produce any output on my system. I have two SSD disks. One for root/swap and the other is for home.

**Comment by roachsinai** [comment]
If you only have SSD disks, sure you should use `qdbus --system org.freedesktop.UDisks2 | grep SSD`. It should show something.

**Comment by afettouhi** [comment]
Nope comes up empty too for some reason.

**Comment by roachsinai** [comment]
Wierd, try not using `grep` just:

`qdbus --system org.freedesktop.UDisks2`

this command above show multiple lines on my laptop.

**Comment by afettouhi** [comment]
Yes, that gives me my drives

/org/freedesktop/UDisks2/drives/TOSHIBA_VT180_46PP604XP8SU
/org/freedesktop/UDisks2/drives/TOSHIBA_VT180_46MP6010P8TU

I gonna fiddle with this a bit and put into the script. If I get stuck can come back and for some more questions? Was possible to split CPU temp into single core temps as well?

**Comment by roachsinai** [comment]
For CPU core, you could just try `sensors`,

```
hmank ~ » sensors                                   
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +49.0°C  (high = +87.0°C, crit = +105.0°C)
Core 0:        +46.0°C  (high = +87.0°C, crit = +105.0°C)
Core 1:        +49.0°C  (high = +87.0°C, crit = +105.0°C)
```

so just change `sensors | grep -oP 'Package.*?\+\K[0-9.]+'` to `sensors | grep -oP 'Core 0.*?\+\K[0-9.]+'` for Core 0, etc.

**Comment by afettouhi** [comment]
Ah, I think getting the hang of it a bit. one issue I have though is that the fan speed of gpu is not shown. I have a Nvidia GTX 1080.

**Comment by roachsinai** [comment]
Use `sensors` again, if you find words like `fan, 00, RPM` it should be.

**Comment by afettouhi** [comment]
This is my output from sensors

```
[af@andre ~]$ sensors
nct7802-i2c-7-2e
Adapter: SMBus I801 adapter at f000
in0:          +3.31 V  (min =  +0.00 V, max =  +4.09 V)
in1:          +1.19 V  
in2:          +0.00 V  (min =  +0.00 V, max =  +2.05 V)
in3:          +1.25 V  (min =  +0.00 V, max =  +2.05 V)
in4:          +1.27 V  (min =  +0.00 V, max =  +2.05 V)
fan1:           0 RPM  (min =    0 RPM)
fan2:           0 RPM  (min =    0 RPM)
fan3:           0 RPM  (min =    0 RPM)
temp4:        +31.0°C  (low  =  +0.0°C, high = +85.0°C)
                       (crit = +100.0°C)
temp6:         +0.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +34.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +32.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:        +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:        +31.0°C  (high = +80.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +119.0°C)
temp2:        +29.8°C  (crit = +119.0°C)

f71889a-isa-0290
Adapter: ISA adapter
+3.3V:        +3.28 V  
in1:          +0.51 V  (max =  +2.04 V)
in2:          +0.92 V  
in3:          +0.95 V  
in4:          +1.09 V  
in5:          +1.22 V  
in6:          +1.30 V  
3VSB:         +3.39 V  
Vbat:         +3.20 V  
fan1:         754 RPM
fan2:           0 RPM  ALARM
fan3:         565 RPM
temp1:        +34.0°C  (high = +85.0°C, hyst = +81.0°C)
                       (crit = +100.0°C, hyst = +96.0°C)  sensor = transistor
temp2:        +33.0°C  (high = +85.0°C, hyst = +81.0°C)
                       (crit = +100.0°C, hyst = +96.0°C)  sensor = transistor
temp3:        +36.0°C  (high = +70.0°C, hyst = +68.0°C)
                       (crit = +85.0°C, hyst = +83.0°C)  sensor = transistor

pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +37.5°C
```
I have 2 entries of each fan1 to fan3. So if I change to fan1 then the output in the plugin jumps back forth between two values of fan1. Is there a way to specify the one value? Plus I a getting formatting issues with the </u>&nbsp;<u> part is just shows up as that.

**Comment by roachsinai** [comment]
Use this `grep -oP -m2 'fan1.*?\K[0-9.]+' | tail -n1`, from https://stackoverflow.com/a/15135500/6074780

**Comment by afettouhi** [comment]
Again many many thanks for all the help. I have modified the `sysinfo.3s.sh` script to display the temperature of my gpu and individual cpu cores plus the temperatures of my drives. This is what I was using `plasma-applet-thermal-monitor` for. Is there a way to show the temperatures of my 4 cpu cores in a square, where each temp is displayed in each corner and in a row?

**Comment by roachsinai** [comment]
Not sure what do you want. But add `<br>` could turn one row to two rows as the png in README.md, like this:

`echo "CPU&nbsp;Fan<br>${temp%%.*}°&nbsp;${fan_speed}| font=Hack size=12"`

Or you could move the temp of cores under `---`, like cpu usage.

**Comment by afettouhi** [comment]
That brings me part of the way I want to display this. But I am asking is:
I want to display my gpu temp and cpu temp like this
gpu | cpu
and then I want to split up my cpu temp of the for cores into a 2x2 matrix basically without impeding on the gpu temp. Hope this makes more sense.

**Comment by roachsinai** [comment]
No, as kargos not support html table tag, failed to find a way let gpu one row while cpu two rows.

Maybe you could split it to two scripts...

**Comment by afettouhi** [comment]
Ah, I figured as much. Can you two scripts at one or do run them as separate widgets?

**Comment by roachsinai** [comment]
Hmm, one script one kargos plasmoid.

**Comment by afettouhi** [comment]
OK, many thanks again for all you help. I got the script running as I want now. I am displaying my gpu temp cpu core temp like this:
`echo -e "Nvidia:&nbsp;<u>${gpu_temp}</u>°C$bitbar1\n<br>Core1:&nbsp;<u>${temp0%%.*}</u>°C&nbsp;Core2:&nbsp;<u>${temp1%%.*}</u>°C<br>Core2:&nbsp;<u>${temp2%%.*}</u>°C&nbsp;Core3:&nbsp;<u>${temp3%%.*}</u>°C$bitbar"`
with two different fonts. It just switched between each every 3 seconds.

**Comment by roachsinai** [comment]
Glad to hear that!
